### ISSUE TITLE
Update `libs-impl` to `T-libs-impl`

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#1162]
The label was renamed recently. (cc rust-lang/rust-forge#506)

@apiraino expressed interest in updating uses in triagebot, so @rustbot assign @apiraino.

**Comment by apiraino** [comment]
closed by https://github.com/apiraino/triagebot/commit/7cb4d13e4c6244fe02c051bed7e68d888e432cfc

**Comment by camelid** [comment]
👍
