### ISSUE TITLE
Difficulty enabling triagebot on rustup repository

### ISSUE THREAD

**Issue by kinnison** [rust-lang/triagebot#1331]
We're trying to enable support for `@rustbot` particularly for labelling things in the Rustup repository.  We added a `triagebot.toml` file to the top level, but the bot seems to ignore us (e.g. https://github.com/rust-lang/rustup/issues/2733#issuecomment-829530565)

Are we missing a web hook?  If so it's not documented in the wiki :(  If not, what else can we do to help debug/enable this?

cc @Mark-Simulacrum @workingjubilee @jyn514

**Comment by Mark-Simulacrum** [comment]
triagebot needs to be added to the permissions; I've done so now and updated the wiki to reflect this. Thanks!
