### ISSUE TITLE
allow queries to operate on multiple repositories at once

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/triagebot#1341]
The [lang-team agenda report](https://github.com/rust-lang/triagebot/blob/master/src/bin/lang-agenda.rs) currently includes nominated items from rust-lang/reference, rust-lang/rust, and rust-lang/rfcs:

https://github.com/rust-lang/triagebot/blob/977a5b6ab86f3b8988ecf0ae2bb0e2e69f21e441/templates/lang_agenda.tt#L34-L36

https://github.com/rust-lang/triagebot/blob/977a5b6ab86f3b8988ecf0ae2bb0e2e69f21e441/templates/lang_agenda.tt#L42-L48

We should be including more repositories. To that end, I would like to collapse all three repositories into one category.

In terms of the code, we should generalize the queries from operating on a single repository to a vector of repositories. I started a branch to do this but hit some difficulties I never had time to resolve:

https://github.com/nikomatsakis/triagebot/tree/queries-on-multiple-repositories

We would probably try to be less clever with the iterators and make things build. =) In other words, just add a nested loop around the `call` method in the `Action` impl for `Step`:

https://github.com/nikomatsakis/triagebot/blob/queries-on-multiple-repositories/src/actions.rs#L52-L54

**Comment by sladyn98** [comment]
https://github.com/sladyn98/triagebot/tree/multiple-repo-query 
Added just the vector for the repos, are we iterating over the repos for the `call` method ?

**Comment by nikomatsakis** [comment]
@sladyn98 right! I think we should apply the same query to each repo in the list. Note that you will have to modify the folks who create those structs to use `vec!["foo"]`

**Comment by sladyn98** [comment]
@nikomatsakis Yeah makes sense, just so that I I understand it correctly

```
            .flat_map(|Query { repos, queries }| repos.iter().map(move |repo| (repo, queries)))
```
In this line for instance we would now be iterating over the `repos` vector and so the folks creating the `Query` struct would need to now use a particular index of the repo ?

**Comment by spastorino** [comment]
@nikomatsakis @sladyn98 is there any reason you don't want to follow the same approach the prioritization wg is following?. https://github.com/rust-lang/triagebot/blob/master/src/agenda.rs#L83-L86

Basically push a new `Query` to the actions list.

**Comment by nikomatsakis** [comment]
Another alternative would be to make a macro for declaring the queries as well; I considered that.

**Comment by apiraino** [comment]
> @nikomatsakis Yeah makes sense, just so that I I understand it correctly
> 
> ```
>             .flat_map(|Query { repos, queries }| repos.iter().map(move |repo| (repo, queries)))
> ```
> 
> In this line for instance we would now be iterating over the `repos` vector and so the folks creating the `Query` struct would need to now use a particular index of the repo ?

(apologies, just saw this thread now after Santiago's ping)

The only (perhaps meaningful) difference I can spot after a quick look at the code is that there are two blocks of queries: one that get the full Github issue body and another that just counts issues.
If I understand correctly, the intent expressed is to conflate in a single iteration all queries, correct? In this case I /think/ it can be done but then there is a bit of additional legwork to separate the results of the two queries blocks ( e.g. splitting them again by `QueryKind::List`).

So, I'm in favor or rethinking a bit the logic as long as the codebase stays "beginner-friendly" :-)

**Comment by nikomatsakis** [comment]
Done!
