### ISSUE TITLE
Assign labels with spaces

### ISSUE THREAD

**Issue by steffahn** [rust-lang/triagebot#1372]
[relevant Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/A.20way.20to.20self-label.20soundness.20issues.3F) ([in the archive](https://zulip-archive.rust-lang.org/122651general/88362Awaytoselflabelsoundnessissues.html))

On my quest to find a way to self-label `I-unsound 💥` I’m getting the feeling that rustbot doesn’t offer any way at all to set labels that contain any spaces. From my limited understanding of the source code it looks like the tokenizer understands quoted strings, but the labels parser doesn’t allow such quoted strings for the label name. I would’ve expected something like `@rustbot label "I-unsound 💥"` to work, but it doesn’t currently work. There’s also the relevant question on whether `@rustbot label -"I-unsound 💥"` or `@rustbot label "-I-unsound 💥"` or both options would be the way to remove the label again.

**Comment by nikomatsakis** [comment]
I'm tempted to say the problem is the label name :)

**Comment by nikomatsakis** [comment]
Or, alternatively, maybe we could load the labels and strip off trailing emojis and whitespace? it'd be nice if you could just type `I-unsound`.

**Comment by steffahn** [comment]
The label was already renamed ;-)

**Comment by steffahn** [comment]
Might be useful to do the whitespace+emoji stripping if there is demand for having the 💥 back.

**Comment by nikomatsakis** [comment]
Seems like we can close this issue, then?

**Comment by steffahn** [comment]
I suppose we can.
