### ISSUE TITLE
add "rustbot note" command to amend OP with notes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/triagebot#1427]
I would like to have a `@rustbot note x` command used like:

```rust
@rustbot note summary

details details details
```

This command will add a link to the OP like

```
### Notes

* ["summary" by @username](link-to-comment)
```

This can be used to allow people to add comments or other significant notes.

**Comment by Mark-Simulacrum** [comment]
I'd like to put the summary in a block quote or only support a few keywords (e.g., summary, nomination-{team}) to avoid accidentally adding a vector to run privileged commands. Not sure if we handle that too well right now, but this seems like an easy thing to address.
