### ISSUE TITLE
lang agenda: include concerns and FCP notes

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/triagebot#1592]
One of the items in the lang-agenda dumps out the proposed FCPs:

https://github.com/rust-lang/triagebot/blob/bc415ec002845aa0c90a28df5457b666381769f2/templates/lang_agenda.tt#L46-L51

It would be awesome to include registered comments and the like.

**Comment by chazkiker2** [comment]
as one who is less familiar with the lang-agenda goings-on, not 100% certain what you mean by registered comments.

would you be willing to clarify?

Given the following description, assuming it’s accurate, would I be correct to assume you mean the “preceding summary comments” that come before the FCP (described in the second sub-bullet)?

![C8A215C4-B6A9-4280-BD35-20FE6F3667C2](https://user-images.githubusercontent.com/70249988/158713134-91ebfe59-b3dd-4b47-9d97-be2341b27603.png)

**Comment by nikomatsakis** [comment]
Ah, I somewhat mistyped. I meant *registered concerns*. But really I think what I would want to do is to reproduce (a) the summary comment and (b) the content of the FCP comment (which includes a set of checkboxes along with a set of registered concerns).

**Comment by nikomatsakis** [comment]
So as an example, reproducing the content of [this comment](https://github.com/rust-lang/rust/pull/93628#issuecomment-1029383585) would be a start; ideally we'd include [this comment too](https://github.com/rust-lang/rust/pull/93628#issuecomment-1029383577) to give more context.

**Comment by Mark-Simulacrum** [comment]
FWIW, having looked a little into this, it will likely require modifications to the rfcbot API -- it currently only exposes the Markdown of the FCP comment. Maybe it's enough to inline those, but IIRC one of the *additional* problems is that there's no way to ask the rfcbot API for issues which are under FCP for a particular team (though that information is presumably tracked somehow -- it's displayed on rfcbot.rs). I'm capable of reviewing and deploying changes there, though; see https://github.com/rust-lang/rfcbot-rs/ for the source code.

I'm significantly less familiar with rfcbot than triagebot, so am not really able to point in the right direction though.

**Comment by Mark-Simulacrum** [comment]
The API is https://rfcbot.rs/api/all, by the way -- it technically has the barebones of the right information (e.g., you can pull the comments Niko is looking for from it for sure), but I'm not sure if it's easy to pull everything from it. Maybe starting with what it has is a good first step though -- it's probably easier than doing upstream modifications first :)

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum we know the set of issues already based on github labels, can we ask rfcbot for the markdown test for a particular issue? that'd be a good start.

**Comment by Mark-Simulacrum** [comment]
Not directly, but I think the rfcbot API does contain enough to find it from the full set -- probably a good approach.

**Comment by chazkiker2** [comment]
Thanks for the clarifications, y'all. Familiarizing myself with this now. 

Here's my current understanding.

- @nikomatsakis wants wants the lang agenda to output all proposed FCPs (which it currently does) but for each proposed FCP, include the following: 
  - the content of the bot tracking comment (and presumably the link to said comment) 
    - the comment ID  is available via [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) through the path `fcp.fk_bot_tracking_comment`
    - the content of the comment is available via [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) through the path `status_comment.body`
  - the content of the initiating comment (and presumably the link to said comment)
    - the comment ID is available via [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) through the path `fcp.fk_initiating_comment`
    - the content of the comment is **NOT YET** available via [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) — however, we could get it through hitting GitHub API since we have the initiating comment ID
- @Mark-Simulacrum you're in favor of doing what we can in triagebot now and making upstream changes (to rfcbot) in the future 
  - eventually, we may want to include (for instance) the initiating comment content within the [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) through the bath `initiating_comment.body` or something of the sort 


Outstanding questions: 
- @nikomatsakis, would you be able to point me in the direction of where the lang agenda spits out currently? Is it in a Zulip channel or somewhere else?
- regarding the following quote: 
  > IIRC one of the additional problems is that there's no way to ask the rfcbot API for issues which are under FCP for a particular team (though that information is presumably tracked somehow -- it's displayed on rfcbot.rs)
  - 1. @Mark-Simulacrum would you be able to link to wherever that's displayed in rfcbot? Or are you saying it's in the [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) already?
  - 2. @Mark-Simulacrum & @nikomatsakis — what's the significance of knowing the particular team? Does this affect which FCPs get rendered? (Ties in with the first question about where the lang agenda outputs currently)
- regarding this quote: 
  > we know the set of issues already based on github labels, can we ask rfcbot for the markdown test for a particular issue? that'd be a good start.
  - 1. @nikomatsakis what's the relevance of knowing the labels? Is that what determines the relevant team in an FCP?
  - 2. @nikomatsakis what do you mean by a "markdown test"?

**Comment by chazkiker2** [comment]
Oh also... another outstanding question: 

- @Mark-Simulacrum / @nikomatsakis  Since we're only trying to get *proposed* FCPs — am I correct in saying the way we'd get that from the [rfcbot.rs/api/all endpoint](https://rfcbot.rs/api/all) is to map through each FCP in that list and only pull the ones with `fcp.disposition == "merge"`?

**Comment by nikomatsakis** [comment]
@chazkiker2 

The template actually lives in this repo! It is generated by `cargo run --bin lang-agenda` or something like that. The [template itself is here](https://github.com/rust-lang/triagebot/blob/master/templates/lang_agenda.tt) but the binary and wrapper is invoked here:

https://github.com/rust-lang/triagebot/blob/2a37c453c01f0d50d5266cab2318a729eb217f64/src/bin/lang.rs#L12-L13

which in turn uses this helper:

https://github.com/rust-lang/triagebot/blob/2a37c453c01f0d50d5266cab2318a729eb217f64/src/agenda.rs#L440

**Comment by nikomatsakis** [comment]
> what's the significance of knowing the particular team? Does this affect which FCPs get rendered? (Ties in with the first question about where the lang agenda outputs currently)

I actually don't think you need to worry about that. The agenda is already identifying issues tagged with the appropriate team. We just want to add extra info for particular issues.

**Comment by nikomatsakis** [comment]
> what's the relevance of knowing the labels? Is that what determines the relevant team in an FCP?

Yes. The issues tagged with T-lang are those that are waiting on a lang team decision.

> what do you mean by a "markdown test"?

 Typo, I meant "markdown *text*"

**Comment by nikomatsakis** [comment]
@chazkiker2 

> Since we're only trying to get proposed FCPs ...

Right now, the list of issues is generated by querying github. I think that is working fine, so potentially we could just consult the RFC bot for particular issues, and not to generate the list itself, but I'm not sure how the API is setup. I also think it would be fine to consult the list -- the only catch is that some of the things in FCP, I realize, may be using the "rustbot second" system as well, so we'd have to account for that.

(We need to bring those two into more harmony.)
