### ISSUE TITLE
Rustbot doesn't check initial message when opening issue

### ISSUE THREAD

**Issue by mati865** [rust-lang/triagebot#16]
Example shown here: https://github.com/rust-lang/rust/issues/61266

Rustbot didn't do anything when I opened issue but when I copy-pasted the command to the comment it changed labels.

**Comment by mati865** [comment]
Still doesn't work: https://github.com/rust-lang/rust/issues/62558

**Comment by pietroalbini** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I've double checked and it does appear to work when testing in both other repositories and rust-lang/rust. I'm not sure what went wrong this morning. See for example https://github.com/rust-lang/rust/issues/62563 where it did in fact work.

Unfortunately we don't have any logging today on the server about what we're doing (something I definitely want to fix) so right now I think there's not much we can say here beyond "hopefully not again".
