### ISSUE TITLE
Add a `@triagebot read` command for zulip

### ISSUE THREAD

**Issue by jackh726** [rust-lang/triagebot#1613]
In many team meetings, there is often a doc everyone starts by reading. Usually someone manually adds the 📖 and ✅ emojis for people to click when they start and finish reading, respectively. It would be nice to just be able to do `@triagebot read`.

**Comment by Mark-Simulacrum** [comment]
This should mostly be a matter of replicating the existing end-topic/end-meeting support.

**Comment by apiraino** [comment]
I'll give a stab at this 

@rustbot claim
