### ISSUE TITLE
@rustbot ready and @rustbot author erroring out in a few cases

### ISSUE THREAD

**Issue by JohnCSimon** [rust-lang/triagebot#1651]
on this PR: https://github.com/rust-lang/rust/pull/95696#issuecomment-1242892564

Tried using `@rustbot ready` shortcut to switch labels and got an error 
> Error: The "Ready" shortcut only works on pull requests.

I don't know what is different about this pull request that produces such an error.

Zulip:
https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/.40rustbot.20author.20not.20working

**Comment by joboet** [comment]
Another example: https://github.com/rust-lang/rust/pull/101442#issuecomment-1242932619
