### ISSUE TITLE
Add ability to ping WGs members using triagebot

### ISSUE THREAD

**Issue by spastorino** [rust-lang/triagebot#169]
We've [agreed on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta/topic/ICE.20breaker.20self-subscribing.20github.20team) that is going to be great if we can have a way of pinging WG members (which are not part of rust-lang github org) using triagebot.

People is already able to sign up by themselves to WGs, just by sending a PR to the team repo on github. We would stick with that idea and encourage people to do so.

This issue is about being able to reach them out. We want a command like `@rustbot icebreaker llvm` that would add a github comment reaching out all the members of that working group with a text that looks like ...

```
Hey LLVM icebreakers! This bug has been identified as a good
"LLVM ice-breaking candidate". In case it's useful, here are some
[general instructions](link) for tackling these sorts of bugs. Maybe take a look?

cc @foo @bar @baz ...
```

Where, the first part of that text is a predefined text that's specific to the working group. Every working group has a very similar text but it's not exactly the same. Specifically the link to instructions is going to be different.

And then, in the cc part, the bot figures out the list of members it needs to mention.

**Comment by Mark-Simulacrum** [comment]
Ideally (from an implementation perspective) the command here would be something like `@rustbot ping wg-llvm-icebreakers` I think? We basically want to match the naming in the team repo instead of creating arbitrary maps I think...

**Comment by pietroalbini** [comment]
> Where, the first part of that text is a predefined text that's specific to the working group. Every working group has a very similar text but it's not exactly the same. Specifically the link to instructions is going to be different.

Where would you like that to be configured? The team repo or the `triagebot.toml` at the root of the rustc repo?

**Comment by nikomatsakis** [comment]
I think the command "ping" seems fine.

I think the team repo seems best, in terms of where this should be documented.

I'm not sure if this should be classified as a *working group* or not. We use that term for a lot of things right now (I think too many, partly my fault) and this feels distinct from other uses of the term. I'm reluctant to add another. That said, I'm not sure what else to call it. =) I mean maybe we just call it `ICE-breaker-llvm`? In terms of the file hierarchy, we could just have "icebreaker-llvm.toml"?

If we were to list them on the web page (which we don't necessarily have to do), we'd list them as "LLVM ICE breakers" with a link to the page about what this means?

Also, I think the command text could probably be the same for all the "ICE-breaker" groups, but the link would vary. So we could hard-code most of the text and just configure the link.

One final thing: the command should also apply the ICEBreaker-LLVM label.

**Comment by pietroalbini** [comment]
> I mean maybe we just call it ICE-breaker-llvm? In terms of the file hierarchy, we could just have "icebreaker-llvm.toml"?

Not really, as that would be considered a team, which would for example include the members in `all@`.

> If we were to list them on the web page (which we don't necessarily have to do), we'd list them as "LLVM ICE breakers" with a link to the page about what this means?

If ICE breakers are in the team repo we can surely list them.

**Comment by nikomatsakis** [comment]
> Not really, as that would be considered a team

I guess we'd have to extend the team repo logic a bit then

**Comment by Mark-Simulacrum** [comment]
@pietroalbini would probably be the best bet on those team repo changes -- I myself am not super familiar with the code, though could probably figure it out if needed (not sure how much time Pietro has these days).

**Comment by pietroalbini** [comment]
I'll probably won't have time to work on the team repo side this week.

**Comment by Mark-Simulacrum** [comment]
@rustbot ping wg-meta

Testing the new functionality out...

**Comment by Mark-Simulacrum** [comment]
@rustbot ping wg-meta

And now...

**Comment by Mark-Simulacrum** [comment]
Okay so that looks like exactly what we wanted, I believe.

The configuration for the above ping can be seen in this repository: https://github.com/rust-lang/triagebot/blob/master/triagebot.toml

I'll re-deploy triagebot's server shortly so that the changes are live for all repositories and can be used on rust-lang/rust for example. We don't currently try to detect >50 users in the team so that'll be a potential problem, but not really one we can easily avoid, so I wouldn't worry too much about it just yet. One solution might be to have triagebot send an email directly instead of a GH notification or just split into two comments...

**Comment by Mark-Simulacrum** [comment]
Closing as we've added this functionality... we'll want a PR to rust-lang/rust to add the config there but that should be a matter for y'all not this repo :)

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum one question btw -- can anybody do pings? Do we want some sort of access control? I guess we can conceivably wait until we have a problem... but I think it'd make sense to require "triage" access or something similar.

**Comment by nikomatsakis** [comment]
Also, I documented this feature in the wiki here https://github.com/rust-lang/triagebot/wiki/Pinging

**Comment by Mark-Simulacrum** [comment]
Right now we allow anyone to do so since but I can easily constrain down to essentially all@ (teams + WGs). Seems reasonable to do that.
