### ISSUE TITLE
Create a documentation book

### ISSUE THREAD

**Issue by ehuss** [rust-lang/triagebot#1697]
I'd like to move the documentation from the wiki to an mdbook published on gh-pages. The intent is to have something that is organized a little better, and so that any changes or new features can update the documentation within the same PR when they are introduced. I'd also like to move the documentation from https://forge.rust-lang.org/platforms/zulip/triagebot.html to this book as well so there is only one place where the documentation lives.

I'd also like to organize the documentation a little better so it has clearer sections for users versus administrative-oriented things like how to configure a feature. I'd like it to be a little more user-centric so that information about how to use a feature is up-front, with information about how to configure `triagebot.toml` is perhaps lower down. And to have a consistent organization between the pages for the different features.

Another intent is to then address #629 by updating some of the bot commands to point to this new book.

Does that sound like something that there would be interest in?

**Comment by apiraino** [comment]
Opened a Zulip thread to discuss [this issue](https://rust-lang.zulipchat.com/#narrow/stream/224082-triagebot/topic/Create.20a.20documentation.20book)

**Comment by ehuss** [comment]
Posted https://github.com/rust-lang/rust-forge/pull/687 to address this.
