### ISSUE TITLE
Testing SnoozeThis (please ignore)

### ISSUE THREAD

**Issue by Jille** [rust-lang/triagebot#1709]
Hey there. We were asked to integrate [SnoozeThis](https://www.snoozethis.com/) with rustbot. I want to do some testing, so I'm creating this issue for that. Sorry for the spam.

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to Jille, add label invalid

**Comment by dev1-SnoozeThis** [comment]
I don't have privileges to execute this action. Please install the SnoozeThis GitHub app (https://github.com/apps/snoozethis).

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to Jille, add label invalid

**Comment by dev1-SnoozeThis** [comment]
Unknown user (or not a collaborator): Jille

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to Jille, add label invalid

**Comment by dev1-SnoozeThis** [comment]
Unknown label: invalid. Please check syntax or create label first.

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to Jille, add label invalid

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/h8OPspeo01I) I will wait until Tue, 18 Jul 2023 21:03:54 CEST and then assign to @Jille and add label invalid.

@rustbot label S-snoozed
@rustbot claim

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot label +invalid
@rustbot assign @Jille

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 15 seconds -> assign to tgmpje, remove label invalid

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/2bgeUdotsv8) I will wait until Tue, 18 Jul 2023 21:05:24 CEST and then assign to @tgmpje and remove label invalid.

@rustbot label S-snoozed

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot label -invalid
@rustbot assign @tgmpje

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to tgmpje

**Comment by dev1-SnoozeThis** [comment]
Unknown user (or not a collaborator): tgmpje

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds -> assign to tgmpje

**Comment by dev1-SnoozeThis** [comment]
Can't assign to user tgmpje (not a collaborator?)

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/IhCz4uxn7bY) I will wait until Tue, 18 Jul 2023 21:28:14 CEST and then add a comment.

@rustbot label S-snoozed

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot release-assignment

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/NIphOSk9RPQ) I will wait until Tue, 18 Jul 2023 21:28:59 CEST and then add a comment.

@rustbot label S-snoozed
@rustbot claim

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot release-assignment

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/udSiLGKMtg8) I will wait until Tue, 18 Jul 2023 22:39:42 CEST and then add a comment.

@rustbot label S-snoozed
@rustbot claim

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot release-assignment

**Comment by Jille** [comment]
@dev1-SnoozeThis wait 30 seconds

**Comment by dev1-SnoozeThis** [comment]
(https://conquistador.snoozeth.is/VCjaDqGRSIs) I will wait until Tue, 18 Jul 2023 22:50:25 CEST and then add a comment.

@rustbot label S-snoozed
@rustbot claim

**Comment by dev1-SnoozeThis** [comment]
Resolved.

@rustbot assign @Jille

**Comment by Jille** [comment]
Testing testing @rustbot claim

**Comment by joshtriplett** [comment]
Does the bot pay attention in backquotes?
`@rustbot label invalid`

**Comment by Jille** [comment]
@SnoozeThis wait 30 seconds -> tell rustbot label invalid

**Comment by SnoozeThis** [comment]
Sorry, I don't understand "tell rustbot label invalid"

**Comment by Jille** [comment]
Oops. Didn't deploy yet.

@SnoozeThis wait 30 seconds -> tell rustbot label invalid

**Comment by SnoozeThis** [comment]
(https://snoozeth.is/zcmF6R0AZq8) I will wait until Tue, 25 Jul 2023 22:29:41 CEST and then mention rustbot.

@rustbot claim.

**Comment by SnoozeThis** [comment]
Resolved.

@rustbot label invalid
@rustbot release-assignment.

**Comment by ehuss** [comment]
I'm going to close, assuming the experiments are over. Feel free to reopen if you need to do something else.
