### ISSUE TITLE
When a PR is closed cleanup labels that are not useful anymore

### ISSUE THREAD

**Issue by apiraino** [rust-lang/triagebot#1732]
When PRs are closed (therefore _not_ merged), the review labels (`S-waiting-on-author` or `S-waiting-on-review`) are not removed. Since they are not useful anymore they can be removed. Take into account both ways that a PR can be closed:
- Using the web UI (click close button)
- `@rustbot close`
(I think they are two separate code paths in the triagebot labels/comments handling logic)

This small cleanup can help f.e. when looking for all PRs waiting on a review: the `is:open` filter would not be needed anymore.

I'm probably forgetting other labels that can be removed as well.

**Comment by Mark-Simulacrum** [comment]
I feel like the costs of doing this (extra code, opportunity for bugs when a PR is closed + opened in quick succession...) are significantly higher than adding is:open to the search query, if that's the only motivation.

**Comment by apiraino** [comment]
main motivation is trying to keep the issue tracker a bit tidy. But if you think there are too many _unknown unknowns_ I will just close this :slightly_smiling_face: 

For reference, we have now:
- [3000 PRs closed with label `S-waiting-on-author`](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Aclosed+label%3AS-waiting-on-author)
- [5380 PRs closed with label `S-waiting-on-review`](https://github.com/rust-lang/rust/pulls?q=is%3Apr+is%3Aclosed+label%3AS-waiting-on-review)

(these numbers don't tell the whole story, of course)

**Comment by Mark-Simulacrum** [comment]
I'd be happy to do a cron task that does this after 7 days of PR being closed or something if you want? But I don't think I understand the cost to your scripts yet.

**Comment by apiraino** [comment]
thanks for the suggestion, I'll think about it.
