### ISSUE TITLE
triagebot rfc_helper cannot deal with the file being renamed to the RFC number

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/triagebot#1803]
The RFC process says

> Now that your RFC has an open pull request, use the issue number of the PR to update your 0000- prefix to that number.

However, rfcbot will create the "Rendered" link to point to the file "0000-*", which will then be a dead link that one has to manually update. The bot should probably update this link automatically?

**Comment by ehuss** [comment]
I'm going to reopen, since I don't think #1848 quite resolves this issue since it doesn't update for pushes.
