### ISSUE TITLE
Add more unauthenticated labels triagebot.toml

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/triagebot#1812]
As an unauthorized user I can't help triage issues, not even my own.
[The docs](https://forge.rust-lang.org/triagebot/labeling.html#permissions) say that most labels should be allowed for everyone, yet only `["bug", "invalid", "question", "enhancement"]` are allowed.

**Comment by apiraino** [comment]
Do you have suggestions about which labels should not require authorization i.e. be open to everyone?
