### ISSUE TITLE
Find some way to work around github not running CI on GHA-created PRs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/triagebot#1864]
PRs created in GHA do not trigger CI. That is a problem when combined with merge queues, where a PR will only be considered ready-to-land when CI passes. The best work-around I know of so far is to close and re-open the PR, which *will* trigger CI.

It might make sense to have a bot do the close-and-reopen automatically, just so that CI has generally already run by the time a human looks at the PR.

**Comment by RalfJung** [comment]
Thanks!

Do we need to configure something to enable this in Miri, or should it "Just Work (TM)"?

**Comment by Mark-Simulacrum** [comment]
You'll need to add the empty table to config.toml, the newly added forge docs should have an example.

**Comment by RalfJung** [comment]
Unfortunately this does not seem to work yet: https://github.com/rust-lang/miri/pull/4085.

FWIW another possible modus operandi here might be for the PR description itself to contain `@rustbot reopen` as a signal to please close and reopen the PR.

**Comment by RalfJung** [comment]
In https://github.com/rust-lang/miri/pull/4088 it worked, amazing :) Thanks a lot!
