### ISSUE TITLE
Add command `@rustbot close`

### ISSUE THREAD

**Issue by Centril** [rust-lang/triagebot#19]
Add a command:
```
@rustbot close
```
which will close the issue or PR.

**Comment by gagan0723** [comment]
@Centril I am interested in implementing above command.

It's my baby-steps with `Rust`, but I will try my best together with one other `triage-wg` member.

**Comment by kellda** [comment]
Who should be allowed to close issues or PRs with this command ?

**Comment by Mark-Simulacrum** [comment]
I think we will want to limit it to authenticated users to start, the is_team_member function IIRC.
