### ISSUE TITLE
"meta <idx> <metadata...>" affects index of item

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/triagebot#331]
I sent "meta 6 something or other" to triagebot on Zulip and it correctly set the bullet text for that item, but in the process that item ended up at index 5 instead of remaining at 6 as I would expect.

Assuming someone else didn't run "as dtolnay move ..." at the same time. :)

**Comment by Mark-Simulacrum** [comment]
This should be fixed by a95aa98, we were updating the idx column in the table previously (and had an off by one error in that update). That update is not even necessary though, so that commit removes it.
