### ISSUE TITLE
Ignore "pings" where a user mentions themselves or their own team

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/triagebot#337]
For the purpose of https://triagebot.infra.rust-lang.org/notifications, me doing an "r? @dtolnay" or mentioning rust-lang/libs should not appear as pinging myself.

**Comment by Dylan-DPC** [comment]
Wonder if we could do r?me

**Comment by Mark-Simulacrum** [comment]
@dtolnay to clarify, do you expect self-pings (whether direct or transitive through a team ping) to be ignored? Or just `r? @dtolnay` should be ignored, as well as direct transitive through-team pings?

**Comment by dtolnay** [comment]
Any time I mention myself should not be considered as notifying myself, not just in the case of `r?`. Another common way this happens is if I am quoting someone else's comment.

> @dtolnay to clarify, ...
