### ISSUE TITLE
Highfive integration

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/triagebot#352]
Consider adopting some of the functionality of @rust-highfive into triagebot.

Things like:

- Greeting new contributors
- Heuristics based assignment of PRs to a random reviewer
- Reassigning PRs in response to `r? @username`

These are related to things triagebot already does.

**Comment by ehuss** [comment]
With https://github.com/rust-lang/triagebot/pull/1656, I think this issue can be closed.
