### ISSUE TITLE
Ping aliases for `@rustbot ping the_alias`

### ISSUE THREAD

**Issue by Centril** [rust-lang/triagebot#402]
Instead of having to remember `@rustbot ping icebreakers-cleanup-crew` it would be great if we could add a memorable alias for the group so that I could e.g. write `@rustbot ping cleanup`. We would configure this by adding a list of aliases under a ping section.

**Comment by Mark-Simulacrum** [comment]
fff4611 implements the alias key for the ping configuration; rust-lang/rust can start using it as soon as the change to triagebot.toml lands in the master of that repo. Could you make that PR?

**Comment by Centril** [comment]
I think so yeah; could you add something to the wiki docs btw?
