### ISSUE TITLE
The assignment has failed silently

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/triagebot#41]
See this [comment](https://github.com/rust-lang/rust/issues/62632#issuecomment-511130497). 
Triagebot tried to edit the issue's description and assign them but it seems its work has failed. 
It's nice for the bot to tell us what's happening, i.e. show an error message.

**Comment by Mark-Simulacrum** [comment]
Should be fixed by 185584385ab08912808c4b8bf4d9ed1b57240325 -- I hesitate to push error messages directly to clients; maybe we can eventually add a "something went wrong" message but that doesn't seem too helpful.
