### ISSUE TITLE
Escape angle brackets in issue titles

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/triagebot#422]
GitHub issues with `<` `>` in the title, such as https://github.com/rust-lang/rust/pull/69163, emit html on the notifications page that contains raw angle brackets, which end up treated by the browser as html tags. We should emit these characters as `&lt;` and `&gt;` and similar for any other html characters that need escaping.

Undecided on whether the description given in `add` commands should be escaped or should allow html tags. I think I would lean toward ideally angle brackets in `add` commands should also get escaped.

**Comment by Mark-Simulacrum** [comment]
👍 on escaping both -- I had originally wanted to support Markdown, as well, though currently we do not. I think most use cases for HTML would be satisfied by that (eventual) support.

**Comment by kellda** [comment]
It seems the change should be done here: https://github.com/rust-lang/triagebot/blob/master/src/notification_listing.rs#L27-L30.
Is always using `replace` OK ? Or does it cause a problem performance-wise ?
