### ISSUE TITLE
Add rustbot prioritize command

### ISSUE THREAD

**Issue by spastorino** [rust-lang/triagebot#453]
Would be nice if we have `@rustbot prioritize` command that assigns `I-prioritize` label and also creates a new topic on [Zulip's WG-prioritization stream](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization) requesting the working group to prioritize the in question issue.

Read more about the discussion about this feature request in this [Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20and.20I-nominated).

**Comment by spastorino** [comment]
cc @rust-lang/wg-prioritization

**Comment by Mark-Simulacrum** [comment]
Please also document on this issue the format for the topic (e.g., should it link to the issue?)

A sample topic in Zulip would be good, too.
