### ISSUE TITLE
React when someone applies `I-prioritize`

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/triagebot#464]
Having to leave a `@rustbot prioritize` comment is less convenient than just applying `I-prioritize` along with the other labels, so it would be great if triagebot could notice the label being applied and do its magic (creating the Zulip stream, etc.)

**Comment by Mark-Simulacrum** [comment]
Done. See https://github.com/rust-lang/rust/issues/71113 and accompanying https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2371113.20Normalization.20error.20with.20.60ToOwned.60/near/193891346.

**Comment by spastorino** [comment]
This is awesome and very cool for people with privileges in the repo. Still leaving the command for people that do not have labeling privileges and advertising it around is also a good idea :).

**Comment by Mark-Simulacrum** [comment]
To be clear, command has not been removed (and indeed does not require any authorization today, anyone can invoke it).
