### ISSUE TITLE
Add command/workflow to go from S-waiting-on-author to S-waiting-on-review

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/triagebot#553]
Currently the status labels for PRs are mostly manually updated by triagers, it would be nice if authors of PRs could more easily update the status when it's `S-waiting-on-author` when they believe they have completed the necessary changes.

### Potential Solutions

- Detect when the author has requested a review using GitHub's request review feature and automatically update labels.
- Add some kind of `@rustbot review` command.

I think ideally we would have both, as `@rustbot review` is easy to teach, but more people are using GitHub's review features as it better integrates with GitHub notifications, and the `@rustbot review` command could be implemented so that it uses GitHub's request review feature.

**Comment by kellda** [comment]
I think it has been fixed by #1381...
