### ISSUE TITLE
Exposed AWS Access Key ID Value

### ISSUE THREAD

**Issue by ikaustubhk** [rust-lang/triagebot#628]
Potential security breach. See /.github/workflows/ci.yml

**Comment by bjorn3** [comment]
In the future please report security issues to security@rust-lang.org. See https://www.rust-lang.org/policies/security for more information.

(I am not a member of @rust-lang, so I can't help fix this issue.)

**Comment by pietroalbini** [comment]
The Access Key ID is not a sensitive value, as it's just the identifier of the access key. The secret key is properly protected.
