### ISSUE TITLE
Add an ellipsis at the end of truncated topics

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#640]
Otherwise, it can be confusing since there's no indication of truncation.

Cc @Mark-Simulacrum

This issue has been assigned to @kellda via [this comment](https://github.com/rust-lang/triagebot/issues/640#issuecomment-662510965).

**Comment by Mark-Simulacrum** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/224082-t-release.2Ftriagebot/topic/truncated.20topics

**Comment by kellda** [comment]
@camelid Are you still working on this ?

**Comment by camelid** [comment]
@kellda I was going to, but I haven’t gotten to it yet. Feel free to claim it if you want to work on it
