### ISSUE TITLE
Major Change Proposals accepted zulip notifications trigger twice

### ISSUE THREAD

**Issue by spastorino** [rust-lang/triagebot#666]
As can we seen here https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Support.20const.20parameters.20in.20type.20dependent.20compiler-team.23304/near/202623737 notifications are being triggered twice. cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Should be fixed on master.
