### ISSUE TITLE
Allow adding parts of given labels when some are forbidden

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/triagebot#669]
In [this issue](https://github.com/rust-lang/rust/pull/74062), the bot failed to add my first label because I did not have the right to add the second one.

Could this be done in a way that it adds successful labels even when others are failing ?

**Comment by Mark-Simulacrum** [comment]
This is intentional - we could partially apply labels, in theory, but it doesn't always make sense to do so, and I think an all-or-nothing approach isn't too bad. You can edit comments and that'll rerun the labeling code, though that doesn't work for the issue description today.

**Comment by poliorcetics** [comment]
> This is intentional - we could partially apply labels, in theory, but it doesn't always make sense to do so

My bad then, I'll close. Thanks for the quick answer and sorry for the delay !
