### ISSUE TITLE
Allow anyone to modify certain labels

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#702]
I'm thinking bug, invalid, and question

**Comment by bjorn3** [comment]
There is already the `@rustbot modify labels` command: https://github.com/rust-lang/triagebot/wiki/Labeling

**Comment by camelid** [comment]
Sorry, I wasn't very clear: I meant specifically on this repository.

As far as I can tell, the `triagebot.toml` does not allow it:

https://github.com/rust-lang/triagebot/blob/b1eccd3d37d03be024164a67bcd186413be86807/triagebot.toml#L1-L2
