### ISSUE TITLE
Zulip URL encoding doesn't work for dots

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#712]
### Rustbot link

https://rust-lang.zulipchat.com/#narrow/stream/233931-xxx/topic/Use.20sane.20defaults.20in.20x.py.20compiler-team.23326

### Actual link

https://rust-lang.zulipchat.com/#narrow/stream/233931-t-compiler.2Fmajor-changes/topic/Use.20sane.20defaults.20in.20x.2Epy.20compiler-team.23326

If we compare the Rustbot link (and elaborate the `xxx` to the full stream name) against the actual link, the only difference that I see is that the actual link encodes the `.` in `x.py` as `.2E`, whereas Rustbot encodes it as just `.`.

From what I see in the rest of the link, it looks like Zulip encodes special characters as a . and then the ASCII hex code. Because of that, it seems a . must be encoded as its hex code.

Cc https://github.com/rust-lang/triagebot/issues/701#issuecomment-660532531

Cc @Mark-Simulacrum

**Comment by camelid** [comment]
Relevant code? https://github.com/rust-lang/triagebot/blob/823fd7fe45ce3f86095d29e2a1b0294d69870b07/src/zulip.rs#L337-L359

**Comment by kellda** [comment]
Seems fixed since #653

**Comment by Mark-Simulacrum** [comment]
I would like to add a test, then, just to make sure we don't regress this bit in the future.
