### ISSUE TITLE
Assignment for non-org members

### ISSUE THREAD

**Issue by nbdd0121** [rust-lang/triagebot#750]
Currently rustbot assigns itself for `@rustbot claim` by users without permission, I believe this is due to the API returning error when a non-org member is assigned, so I emailed GitHub support about this issue:

Gary Guo: Jun 22, 2020, 11:03 PM UTC
> In the UI (https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users):   You can assign up to 10 people to each issue or pull request, including   yourself, anyone who has commented on the issue or pull request, anyone with   write permissions to the repository, and organization members with read   permissions to the repository. For more information, see "Access   permissions on GitHub."
>
> In the API (https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue):
> NOTE: Only users with push access can add assignees to an issue. Assignees   are silently ignored otherwise. 
>
> So people who has commented   on the issue or pull request can be assigned in the UI but not the API. Is   this inconsistency intentional? This is very confusing.

Laurel (GitHub Support): Aug 5, 2020, 7:17 PM UTC
> Hello Gary,
>
> Thank you for contacting GitHub support. Sorry for the delay in responding to this issue. I confirmed   that you can add users who have commented on an issue as an assignee both in   the UI and via the API. The note in the API is in reference to the   permissions required to be able to add an assignee, not the permissions   needed to be an assignee. Please let me know if there is anything else I can   help you with.
>
> Kind regards,
> Laurel

However it seems that this is different from what we experience, because an user who posted `@rustbot claim` certainly would have commented on that issue. Could someone confirm that we are currently indeed not being able to assign users who have commented on an issue as an assignee?

**Comment by nbdd0121** [comment]
Oh, I checked the source code, it seems that it is an incorrect use of the API.

https://github.com/rust-lang/triagebot/blob/77ea0f439501f127e1b682dd5082fabf8a7fa68e/src/github.rs#L514
This only checks if an user can be assigned to *any* issue of the repository, rather than a particular issue.

**Comment by Mark-Simulacrum** [comment]
To my knowledge, there is not a way to check for a particular issue, note that [the check API](https://developer.github.com/v3/issues/assignees/#check-if-a-user-can-be-assigned) does not take an issue.

It would be possible for us to just try and assign without checking, I suppose -- I don't recall if there's some problem there.
