### ISSUE TITLE
Triagebot isn't responding to label requests in rust-lang/www.rust-lang.org

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#765]
I posted this (https://github.com/rust-lang/www.rust-lang.org/issues/1229#issuecomment-674591531):

```
@rustbot modify labels: +A-Infra
```

but nothing happened.

The `triagebot.toml` for rust-lang/www.rust-lang.org is:

https://github.com/rust-lang/www.rust-lang.org/blob/17e264d5a27702fe7f1a6d346f338a6bf28174c7/triagebot.toml

which should allow me to modify labels.

Cc #754

**Comment by camelid** [comment]
Looks like it works in this repo.

@Mark-Simulacrum maybe the same issue that I had in rust-lang/rust-clippy (no write permissions for rustbot)?

**Comment by Mark-Simulacrum** [comment]
Should be fixed.

**Comment by camelid** [comment]
Works now, thanks!
