### ISSUE TITLE
Deleting a label comment makes Rustbot execute the comment

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#766]
Deleting a label comment like `@rustbot modify labels: bug` makes rustbot execute the command. In my case, the original label request didn't work, but once it was fixed I deleted it and rustbot then applied the label.

Not sure if this is considered an issue (probably doesn't matter), but wanted to report it anyway.

@rustbot modify labels: invalid

**Comment by bjorn3** [comment]
@rustbot modify labels: -invalid

The `invalid` label is for when the issue itself is invalid. For example because it was opened by a bot.

**Comment by camelid** [comment]
Huh, I didn’t realize that. I thought it was for invalid behavior, but I guess that’s what `bug` is for. Thanks for pointing that out!

@rustbot modify labels: +bug

**Comment by kellda** [comment]
I may have introduced this in #707 or #708. Could you add a link to the comment where you experienced this bug ?

**Comment by camelid** [comment]
Well, the issue happened when I deleted the comment, so I can't link to it :)

The text was:

```
@rustbot modify labels: +A-Infra
```

**Comment by kellda** [comment]
Ok I think the webhook payload is the same as when the comment is created, except for the `action` field, so the command is run again.
