### ISSUE TITLE
Allow acknowledging all notifications

### ISSUE THREAD

**Issue by camelid** [rust-lang/triagebot#849]
It would probably be helpful for people who get a ton of notifications and want to acknowledge all of them so they can start fresh.

@rustbot modify labels: enhancement

**Comment by jyn514** [comment]
I don't know what you mean here. Triagebot doesn't send out notifications, github does. If you want to clear github notifications, you can do that:

![image](https://user-images.githubusercontent.com/23638587/95003159-5bf08280-05aa-11eb-9066-423986af6a95.png)

**Comment by camelid** [comment]
I mean this: https://triagebot.infra.rust-lang.org/notifications?user=camelid

For example, [you have](https://triagebot.infra.rust-lang.org/notifications?user=jyn514) 622 notifications, and I'm guessing you don't want to manually [`ack <idx>`](https://forge.rust-lang.org/platforms/zulip/triagebot.html#issue-notifications) for each one :)

**Comment by jyn514** [comment]
Oh wow, I didn't know that page existed. Is that documented somewhere?

**Comment by camelid** [comment]
https://forge.rust-lang.org/platforms/zulip/triagebot.html#issue-notifications
