### ISSUE TITLE
Make label a one-word command

### ISSUE THREAD

**Issue by tmandry** [rust-lang/triagebot#892]
I tend to find `@rustbot modify labels to` unwieldy, both to remember and type. At this point I've typed it enough times that I probably won't forget, but I remember having to look up docs several times to remember the incantation I'm supposed to use.

I think `@rustbot label +foo` is just as self-explanatory and easier to remember.

Could we add this as a synonym?

**Comment by Mark-Simulacrum** [comment]
I would be happy to take a PR, should be a matter of modifying https://github.com/rust-lang/triagebot/blob/master/parser/src/command/relabel.rs#L130.
